### ISSUE TITLE
Newbie-type question

### ISSUE THREAD

**Issue by minneapolisdan** [lolmaus/singularity-quick-spanner#1]
`+add-grid(1 3 1)`

Is the plus sign (+) a shortcut for @include? If so, does that require a special library or mixin? It doesn't work for me. 

Also:
Where did you get this? `+sgs-reset(grids)`

I don't see that anywhere in online documentation. 

Thanks!

**Comment by lolmaus** [comment]
> Is the plus sign (+) a shortcut for @include? If so, does that require a special library or mixin? It doesn't work for me.

Use `+` if your file extension is `.sass`. If it's `.scss`, use `@include`.

> Where did you get this? `+sgs-reset(grids)`

https://github.com/at-import/Singularity/blob/v1.7.0/stylesheets/singularitygs/helpers/_settings.scss#L47-L60
